name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    
  bubble: ^1.1.9+1
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.2+1
  firebase_auth: ^0.15.1
  cloud_firestore: ^0.12.11
  modal_progress_hud: ^0.1.3
  http: ^0.12.0+2
  





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
